#!/bin/bash
trash=$HOME/.trashbox

function reremove(){
	if [ `ls -l ./ | wc -l` != "1" ]; then
		echo -e '\n\e[33mSelect recover directory number\n\e[34m'
	else
		echo  "There is no file in TrashBox"
		return 0
	fi 
	select opt in $@
	do
		echo -e '\e[mPlease check dirctory contents table\n'
		echo -e '---------------------------------\e[35m'
		ls $opt -R
		echo -e '\e[m---------------------------------'

		dist=`cat $opt/.recover-dir.log`
		
		echo -e 'This will be copy to\e[32m' $dist
		echo -e -n '\e[mcomfirm (y/n)'
		read cfm
		if [ $cfm = "n" ]; then
			echo -n " continue? (y/n)"
			read cfm
			if [ cfm == "y" ]; then
				continue
			else
				break
			fi
		fi
		
		/bin/rm $opt/.recover-dir.log

		echo -e ''
		echo -e -n  'Do you want to \e[32mpop \e[mfile(s) from manegement Dir (y/n)'
		read cfm
		mkdir -p  $dist
		if [ $cfm = "y" ]; then
			mv -f $opt/* $dist/
			/bin/rm -rfd $opt/
		else
			mv -f $opt $dist/
		fi

		break
	done
}
pushd $trash >/dev/null
reremove *
popd  > /dev/null
