#!/bin/bash
trash=$HOME/.trashbox

function reremove(){
	
	echo -e '\n\e[33mSelect recover directory number\n\e[34m'
	
	select opt in $@
	do
		echo -e '\e[mPlease check dirctory contents table\n'
		echo -e '---------------------------------\e[35m'
		ls $opt -R
		echo -e '\e[m---------------------------------'

		dist=`cat $opt/.recover-dir.log`
		
		echo -e 'This will be copy to\e[32m' $dist
		echo -e '\e[mcomfirm (y/n)'
		read cfm
		if [ $cfm = "n" ]; then
			break
		fi
		
		/bin/rm $opt/.recover-dir.log

		echo -e ''
		echo -e 'Do you want to \e[32mpop \e[mfile(s) from manegement Dir (y/n)'
		read cfm
		if [ $cfm = "y" ]; then
			mv -vf $opt/* $dist
			/bin/rm -rfd $opt/
		else
			mv -vf $opt $dist
		fi

		break
	done
}
reremove $trash/*
